apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-jenkins
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.9.37.148
    path: "/data/test/jenkins"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

