apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-demo-java
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.9.37.148
    path: "/data/test/java"
